CREATE TABLE orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status     VARCHAR(255) DEFAULT 'pending',
    user_id    BIGINT    NOT NULL,
    course_id  BIGINT    NOT NULL,
    snap_url   VARCHAR(255),
    metadata   JSON,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE payment_logs(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR(255) NOT NULL,
    payment_type VARCHAR(255) NOT NULL,
    raw_response JSON         NOT NULL,
    order_id     INTEGER      NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);
