CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    address    TEXT,
    name       VARCHAR(255),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP
);