CREATE TABLE mentors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    profile    VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    profession VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP
);


CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate boolean default false                                                             NOT NULL,
    thumbnail   VARCHAR(255),
    type        VARCHAR(7) CHECK (type IN ('free', 'premium'))                                    NOT NULL,
    status      VARCHAR(9) CHECK (status IN ('draft', 'published'))                               NOT NULL,
    price       INTEGER DEFAULT 0,
    level       VARCHAR(12) CHECK (level IN ('all-level', 'beginner', 'intermediate', 'advance')) NOT NULL,
    description TEXT,
    mentor_id   BIGINT                                                                            NOT NULL,
    created_at  TIMESTAMP                                                                         NOT NULL,
    updated_at  TIMESTAMP,
    FOREIGN KEY (mentor_id) REFERENCES mentors (id) ON DELETE CASCADE
);

